books_and_folks/urls.py
from django.urls import path

from . import views

app_name = 'books_and_folks'
urlpatterns = [
    path('', views.index, name='index'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('authors/', views.AuthorList.as_view(), name='authors'),
    path('book/<int:pk>/', views.book_detail, name='book'),
    path('books/', views.books_list, name='books'),
    path('publisher/<int:pk>/', views.publisher_detail, name='publisher'),
    path('publishers/', views.publishers_list, name='publishers'),
    path('store/<int:pk>/', views.store_detail, name='store'),
    path('stores/', views.stores_list, name='stores'),
]

eight_pages/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='browse/', permanent=False)),
    path('admin/', admin.site.urls),
    path('browse/', include('books_and_folks.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

books_and_folks/models.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def get_books(self):
        return ', '.join([book.name for book in self.books_auths.all()])

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=300)

    def get_absolute_url(self):
        return reverse('publisher-detail', args=[str(self.pk)])

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=300)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.FloatField()
    authors = models.ManyToManyField(Author, related_name='books_auths')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, related_name='books_pubs')
    pubdate = models.DateField()

    def __str__(self):
        return self.name

    def get_authors(self,):
        return ', '.join([author.name for author in self.authors.all()])


class Store(models.Model):
    name = models.CharField(max_length=300)
    books = models.ManyToManyField(Book, related_name='stores_books')

    def __str__(self):
        return self.name

books_and_folks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, Count
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import DeleteView, CreateView, UpdateView


from .models import Author, Book, Publisher, Store


def index(request):

    return render(request, 'index.html')


def books_list(request):
    books_and_authors = Book.objects.prefetch_related('authors').all()

    return render(request, 'books.html', {'books_and_authors': books_and_authors})


def book_detail(request, pk):
    book = get_object_or_404(
        Book.objects.prefetch_related('authors', 'stores_books').select_related('publisher').all(),
        pk=pk)

    return render(request, 'bookdetail.html', {'book': book})


class AuthorList(generic.ListView):
    model = Author
    paginate_by = 4
    queryset = Author.objects.all().annotate(Count('books_auths'))
#
# def authors_list(request):
#     authors_and_books_amt = Author.objects.all().annotate(Count('books_auths'))
#
#     return render(request, 'authors.html', {'authors_and_books_amt': authors_and_books_amt})


class AuthorDetail(generic.DetailView):
    model = Author


def publishers_list(request):
    pubs_books_and_stuff = Publisher.objects.all().annotate(Count('books_pubs')).annotate(Avg('books_pubs__rating'))

    return render(request, 'publishers.html', {'pubs_books_and_stuff': pubs_books_and_stuff})


def publisher_detail(request, pk):
    pubbie = get_object_or_404(
        Publisher.objects.prefetch_related('books_pubs', 'books_pubs__authors').all().annotate(Count('books_pubs')),
        pk=pk,
    )

    return render(request, 'publisherdetail.html', {'pubbie': pubbie})


def stores_list(request):
    stores_books = Store.objects.prefetch_related('books').all().annotate(Count('books')).annotate(Avg('books__price'))

    return render(request, 'stores.html', {'stores_books': stores_books})


def store_detail(request, pk):
    store = get_object_or_404(
        Store.objects.prefetch_related('books', 'books__authors').all().annotate(Count('books')),
        pk=pk,
    )

    return render(request, 'storedetail.html', {'store': store})


class AuthorCreate(LoginRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('books_and_folks:authors')


class AuthorUpdate(LoginRequiredMixin, UpdateView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('books_and_folks:authors')


class AuthorDelete(LoginRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('books_and_folks:authors')

books_and_folks/templates/authordetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Detail</title>
</head>
<body>
{% if author %}
<h1> Behold: {{ author.name }} !</h1>
<hr>
<p>This author whrote {{ author.books_auths__count }} books:</p>
  {% for book in author.books_auths.all %}
    <p><a href="{% url 'books_and_folks:book' book.pk %}">{{ book.name }}</a> ( {{ book.pages }} pages )</p>
  {% endfor %}
<hr>
<a href="{% url 'books_and_folks:authors' %}">Go to authors list</a>
{% else %}
<a href="{% url 'books_and_folks:books' %}">Go to authors list</a>
{% endif %}
</body>
</html>

books_and_folks/templates/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
<p><a href="{% url 'books_and_folks:index' %}">Go to Homepage</a></p>
<h1>Authors list:</h1>
{% if authors_and_books_amt %}
{% for author in authors_and_books_amt %}
      <li>
        <a href="{% url 'books_and_folks:author' author.pk %}">{{ author.name }}</a>
          ( Wrote {{ author.books_auths__count}} books!)
      </li>
{% endfor %}
{% else %}
<p>No authors available for browsing, sorry.</p>
{% endif %}
</body>
</html>

books_and_folks/templates/bookdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Detail</title>
</head>
<body>
{% if book %}
<h1>{{ book.name }}</h1>
<p> This title was written by
    {% for author in book.authors.all %}
       <a href="{% url 'books_and_folks:author' author.pk %}">{{ author.name }}</a> ({{ author.age }} years),&nbsp;
    {%endfor%}
<hr>
You can purchase this book at:
  {% for store in book.stores_books.all %}
    <a href="{% url 'books_and_folks:store' store.pk %}">{{ store.name }}</a>
  {% endfor %}
<hr>
<p>Pages: {{ book.pages }}</p>
<p>Rating: {{ book.rating }} / 5.0</p>
<p>Price: {{ book.price }}</p>
<p>Published by: <a href="{% url 'books_and_folks:publisher' book.publisher.pk %}">{{ book.publisher }}</a></p>
<hr>
<a href="{% url 'books_and_folks:books' %}">Go to book list</a>
{% else %}
<a href="{% url 'books_and_folks:books' %}">Go to book list</a>
{% endif %}
</body>
</html>

books_and_folks/templates/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books</title>
</head>
<body>
<p><a href="{% url 'books_and_folks:index' %}">Go to Homepage</a></p>
<h1>Book list:</h1>
{% if books_and_authors %}
{% for book in books_and_authors %}
      <li>
        <a href="{% url 'books_and_folks:book' book.pk %}">{{ book.name }}</a>  ( by
          {% for author in book.authors.all %}
            {{ author.name }}
          {% endfor %}
          )
      </li>
{% endfor %}
{% else %}
<p>Sorry, no books available.</p>
{% endif %}
</body>
</html>

books_and_folks/templates/books_and_folks/author_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
</body>
</html>

books_and_folks/templates/books_and_folks/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Detail</title>
</head>
<body>
{% if author %}
<h1> Behold: {{ author.name }} !</h1>
{% if user.is_authenticated %}
<p><a href="{% url 'books_and_folks:author-delete' author.pk %}">Delete this author</a></p>
{% endif %}
<hr>
<p>This author wrote {{ author.books_auths__count }} books:</p>
  {% for book in author.books_auths.all %}
    <p><a href="{% url 'books_and_folks:book' book.pk %}">{{ book.name }}</a> ( {{ book.pages }} pages )</p>
  {% endfor %}
<hr>
<a href="{% url 'books_and_folks:authors' %}">Go to authors list</a>
{% else %}
<a href="{% url 'books_and_folks:books' %}">Go to authors list</a>
{% endif %}
</body>
</html>

books_and_folks/templates/books_and_folks/author_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
</body>
</html>

books_and_folks/templates/books_and_folks/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p><a href="{% url 'books_and_folks:index' %}">Go to Homepage</a></p>
<h1>Authors list:</h1>
{% if user.is_authenticated %}
<p><a href="{% url 'books_and_folks:author-create'%}">Add another author</a> </p>
{% endif %}
{% if author_list %}
{% for author in author_list %}
      <li>
        <a href="{% url 'books_and_folks:author' author.pk %}">{{ author.name }}</a>
          ( Wrote {{ author.books_auths__count}} books!)
      </li>
{% endfor %}
{% else %}
<p>No authors available for browsing, sorry.</p>
{% endif %}
<br>
{% if is_paginated %}
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                      {% endif %}
                  </span>
          {% endif %}
</body>
</html>

books_and_folks/templates/books_and_folks/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for book in books_list %}
      <li>
        {{ book.name }}
      </li>
    {% endfor %}
</body>
</html>

books_and_folks/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>Hello! Browse this site!</h1>
    <p><a href="{% url 'books_and_folks:authors' %}">Authors</a></p>
    <p><a href="{% url 'books_and_folks:books' %}">Books</a></p>
    <p><a href="{% url 'books_and_folks:publishers' %}">Publishers</a></p>
    <p><a href="{% url 'books_and_folks:stores' %}">Stores</a></p>
</body>
</html>

books_and_folks/templates/publisherdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Publisher</title>
</head>
<body>
{% if pubbie %}
<h1> Here we have {{ pubbie.name }} !</h1>
<hr>
<p>They've already published {{ pubbie.books_pubs__count }} books:</p>
  {% for book in pubbie.books_pubs.all %}
    <li>
        <a href="{% url 'books_and_folks:book' book.pk %}">{{ book.name }}</a> by
        {% for author in book.authors.all %}
          <a href="{% url 'books_and_folks:author' author.pk %}">{{ author.name }}, </a>
        {% endfor %}
        ( Book rating = {{ book.rating }} )
    </li>
  {%endfor%}
<hr>
<a href="{% url 'books_and_folks:publishers' %}">Go to publishers list</a>
{% else %}
<a href="{% url 'books_and_folks:publishers' %}">Go to publishers list</a>
{% endif %}
</body>
</html>

books_and_folks/templates/publishers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Publishers</title>
</head>
<body>
<p><a href="{% url 'books_and_folks:index' %}">Go to Homepage</a></p>
<h1>Publishers list:</h1>
{% if pubs_books_and_stuff %}
{% for publisher in pubs_books_and_stuff %}
      <li>
        <a href="{% url 'books_and_folks:publisher' publisher.pk %}">{{ publisher.name }}</a>;
          Books published: {{ publisher.books_pubs__count }};
          Book average rating: {{ publisher.books_pubs__rating__avg }}
      </li>
{% endfor %}
{% else %}
<p>Sorry, information unavailable.</p>
{% endif %}
</body>
</html>

books_and_folks/templates/storedetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store</title>
</head>
<body>
    {% if store %}
<h1>Welcome to {{ store.name }}</h1>
<hr>
<p> Here available {{ store.books__count }} following titles:
    {% for book in store.books.all %}
       <li>
           <a href="{% url 'books_and_folks:book' book.pk %}">{{ book.name }}</a> by
        {% for author in book.authors.all %} {{ author.name }} {% endfor %} ($ {{ book.price }})
       </li>
    {%endfor%}
<hr>
<a href="{% url 'books_and_folks:stores' %}">Go to stores list</a>
{% else %}
<a href="{% url 'books_and_folks:stores' %}">Go to stores list</a>
{% endif %}
</body>
</html>

books_and_folks/templates/stores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stores</title>
</head>
<body>
<p><a href="{% url 'books_and_folks:index' %}">Go to Homepage</a></p>
<h1>Buy your books in multiple online bookstores:</h1>
{% if stores_books %}
{% for store in stores_books %}
      <li>
        <a href="{% url 'books_and_folks:store' store.pk %}">{{ store.name }}</a>
          (Available {{ store.books__count }} books, average price = {{store.books__price__avg}} )
      </li>
{% endfor %}
{% else %}
<p>Sorry, no info on stores yet.</p>
{% endif %}
</body>
</html>